CREATE TABLE GPS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  gpx CLOB NOT NULL,
  track VARCHAR(256) NOT NULL,
  metadata VARCHAR(1000) NOT NULL,
  waypoint BOOLEAN NOT NULL DEFAULT FALSE,
  created_date TIMESTAMP DEFAULT NOW(),
  updated_date TIMESTAMP
);


